In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# Two-dimension numpy array
a2 = np.array([[1, 2.0, 3.2],
               [4,5,6.5]])

# Three-dimension numpy array
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.2],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](images/Anatomy-of-numpy-array.png)

## Attributes

In [12]:
## To know the (number of dimensions, number of columns, number of rows)
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
# To know the number of dimensions use ndim attribute
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.ndim

1

In [17]:
a3.ndim

3

In [18]:
## knowing the datatype of numpy array
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [19]:
## knowing the size of numpy array
a1.size, a2.size, a3.size

(3, 6, 18)

In [20]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
# Create a DataFrame from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.2
1  4.0  5.0  6.5

## Creating Arrays

In [25]:
simple_array = np.array([1,2,3])
simple_array

array([1, 2, 3])

In [32]:
ones = np.ones((2,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
ones.dtype

dtype('float64')

In [34]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0,2, size=(3,5))
random_array

array([[1, 0, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 1, 1]])

In [37]:
random_array.size

15

In [48]:
random_array_2 = np.random.random((5,3,1))   # (rows, column)
random_array_2

array([[[0.77693734],
        [0.66212022],
        [0.51797418]],

       [[0.71346932],
        [0.86670753],
        [0.78971921]],

       [[0.194263  ],
        [0.14853813],
        [0.39688287]],

       [[0.71197076],
        [0.34809066],
        [0.6754447 ]],

       [[0.30242709],
        [0.5844839 ],
        [0.44605885]]])

In [49]:
random_array_2.shape

(5, 3, 1)

In [47]:
random_array_3 = np.random.rand(5,3,1)
random_array_3

array([[[0.63410222],
        [0.89917437],
        [0.90558374]],

       [[0.4237382 ],
        [0.95666261],
        [0.21019963]],

       [[0.7089762 ],
        [0.05635927],
        [0.36579435]],

       [[0.74357952],
        [0.89487098],
        [0.25809952]],

       [[0.62985409],
        [0.88440292],
        [0.82592291]]])